### ISSUE TITLE
EpubParser fail

### ISSUE THREAD

**Issue by winterdl** [Mantano/mno_streamer_dart#2]
The testing epub load okay with other ebook reader or readium kotlin, but fail with the mno_streamer_dart

test code

```
import 'package:mno_shared/fetcher.dart';
import 'package:mno_streamer/parser.dart';

void main(List<String> arguments) async {
  await testParser('./books/book_test.epub');
}

Future testParser(String fileAtPath) async {
  var pub = await EpubParser().parse(fileAtPath);

  print(pub != null);

  return;
}

```

dart run

output:

```
OEBPS/content.opf
Unhandled exception:
UserException{userMessageId: r2_shared_resource_exception_other, args: [], quantity: null, cause: XmlParserException: ">" expected at 599:10}
#0      Try.getOrThrow (package:mno_commons/utils/try.dart:23:5)
#1      EpubParser._parse (package:mno_streamer/src/epub/epub_parser.dart:96:58)
<asynchronous suspension>
#2      EpubParser.parseWithFallbackTitle (package:mno_streamer/src/epub/epub_parser.dart:145:15)
<asynchronous suspension>

```

Demo and sample book attached
[test_project.zip](https://github.com/Mantano/mno_streamer_dart/files/7210815/test_project.zip)

**Comment by winterdl** [comment]
if I extract the ebook to folder, it will parse okay, I think the problem with ArchiveFetcher, it returns data with missing last character.

The error message: ">" expected at 599:10 , ">" is the last charater of the file.

I add the method readAsString to fetcher.dart:

```
Future<String?> readAsString(String href) => getWithHref(href)
      .use((it) => it.readAsString().then((value) => value.getOrNull()));
```

and test with this code:

```
Future testFetcherString(String fileAtPath) async {
  var fetcher = await Fetcher.fromArchiveOrDirectory(fileAtPath);
  var xml = await fetcher?.readAsString('/OEBPS/content.opf');
  print(xml);
}
```

the output missing the last character ">":

<img width="538" alt="Screen Shot 2021-09-23 at 9 14 32 AM" src="https://user-images.githubusercontent.com/302480/134445618-4a88e68f-01aa-46fb-b03c-d5e82b0b2fe9.png">

and this is the original file

<img width="621" alt="Screen Shot 2021-09-23 at 9 34 49 AM" src="https://user-images.githubusercontent.com/302480/134447015-736006dc-c36e-421f-97ff-04db6af5cdf4.png">

**Comment by yteitel** [comment]
Thank you very much for the issue. It was really helpful to have an example and a detailed description.
The fix is done in the commit above.
I will publish an update on pub.dev
